import Link from "next/link";

const features = [
  ["Beginner / Free modes", "Choose guided explanations or a focused independent workspace."],
  ["Sample bank and reset", "Load a ready customer with two accounts or clear all temporary records."],
  ["Searchable request playground", "Find an operation by method, resource, or action, then edit its complete URL, headers, token, and JSON body."],
  ["Request Inspector", "Review the exact request and response headers, then copy it as cURL."],
  ["Automation code generator", "Turn a sent request into Rest Assured Java or Playwright TypeScript with assertions."],
  ["Response learning tools", "Copy or download response JSON, clear the panel, and read a plain-language explanation of every result."],
  ["Assertions", "Check status codes, JSON paths, and response time automatically."],
  ["Negative testing", "Practise beginner and advanced errors including 403, 405, 415, 429, and 503."],
  ["Banking API Quest", "Build method, URL, and JSON manually across ten missions, then copy a completion summary with score and practised statuses."],
  ["Session dashboard", "See request history, token status, and generated IDs."],
  ["Swagger reference", "Explore documented endpoints and use Try it out."],
  ["Postman collection", "Download organized requests with variables and automatic scripts."],
];

const statuses = [["200","OK"],["201","Created"],["204","No Content"],["400","Bad Request"],["401","Unauthorized"],["403","Forbidden"],["404","Not Found"],["405","Method Not Allowed"],["409","Conflict"],["415","Unsupported Media Type"],["422","Cannot Process"],["429","Too Many Requests"],["503","Service Unavailable"]];

export default function GuidePage() {
  return <main className="guide-page">
    <header className="guide-nav"><Link href="/"><span>B</span><strong>BetappaBharath <em>API TestLab</em></strong></Link><nav><a href="#start">Quick start</a><Link href="/challenges">Challenges</Link><a href="#postman">Postman</a><Link href="/swagger">Swagger</Link><a className="guide-primary" href="/#playground">Open practice lab</a></nav></header>
    <section className="guide-hero"><div><p className="guide-kicker">User guide · Banking API TestLab</p><h1>Everything you need to start testing APIs.</h1><p>Learn what the TestLab contains, how banking data connects, and how to test requests from the website or Postman.</p><div><a href="#start">Start with the basics</a><a href="/#playground">Go to practice</a></div></div><aside><b>Recommended first session</b><ol><li>Create a token</li><li>Load the sample bank</li><li>List all customers</li><li>Get one account</li><li>Try a negative test</li><li>Run assertions</li></ol></aside></section>
    <div className="guide-layout"><aside className="guide-toc"><b>On this page</b><a href="#overview">Overview</a><a href="#start">Quick start</a><a href="#flow">Banking flow</a><a href="#features">Features</a><a href="#methods">HTTP methods</a><a href="#assertions">Assertions</a><a href="#negative">Negative testing</a><a href="#postman">Postman</a><a href="#status">Status codes</a><a href="#troubleshooting">Troubleshooting</a></aside>
      <article className="guide-content">
        <section id="overview"><p className="guide-label">01 · Overview</p><h2>What is this website?</h2><p>BetappaBharath Banking API TestLab is a safe practice application for learning API testing. It behaves like a small retail bank, but all customers, accounts, balances, and transfers are temporary simulations.</p><div className="guide-callout"><b>Practice data only</b><p>Never enter real passwords, account numbers, or personal financial information.</p></div></section>
        <section id="start"><p className="guide-label">02 · Quick start</p><h2>Send your first request</h2><div className="guide-steps">{[["Create an access token","Select Generate access token and send the example body. It is automatically attached as Bearer authorization."],["Prepare practice data","Load the sample bank or create a new customer manually."],["Choose an operation","Search by method or action, then select an endpoint under Customers, Accounts, or Money."],["Send and inspect","Read the status, plain-language explanation, JSON response, assertions, and inspector. Copy or download JSON when useful."]].map(([title,copy],index)=><article key={title}><span>{index+1}</span><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></section>
        <section id="flow"><p className="guide-label">03 · Banking flow</p><h2>How records are connected</h2><div className="relationship"><div><span>Customer</span><code>CUST-1001</code></div><b>has one or more</b><div><span>Accounts</span><code>ACC-5001 · ACC-5002</code></div><b>contain</b><div><span>Transactions</span><code>TXN-9001</code></div></div><ul><li>Create Customer returns a Customer ID.</li><li>Create Account uses the Customer ID and returns an Account ID.</li><li>Deposits, withdrawals, transfers, and history use Account IDs.</li><li>A funded account cannot be deleted. Empty its balance first.</li><li>A customer with active accounts cannot be deleted. Remove those accounts first.</li></ul></section>
        <section id="features"><p className="guide-label">04 · Site features</p><h2>What is available?</h2><div className="feature-list">{features.map(([title,copy])=><article key={title}><b>{title}</b><p>{copy}</p></article>)}</div></section>
        <section id="methods"><p className="guide-label">05 · HTTP methods</p><h2>Understand the request type</h2><div className="guide-table"><div><b>Method</b><b>Meaning</b><b>Example</b></div>{[["GET","Read information","List customers"],["POST","Create information","Create an account"],["PUT","Replace all information","Replace customer details"],["PATCH","Change one part","Rename an account"],["DELETE","Remove information","Delete an empty account"]].map(([method,meaning,example])=><div key={method}><span className={`guide-method ${method.toLowerCase()}`}>{method}</span><p>{meaning}</p><p>{example}</p></div>)}</div></section>
        <section id="assertions"><p className="guide-label">06 · Assertions</p><h2>Check whether a response is correct</h2><p>An assertion turns an observation into a repeatable test.</p><ul><li><b>Status:</b> Did the API return the expected 200 or 201?</li><li><b>JSON path:</b> Does a field such as <code>data.id</code> exist?</li><li><b>Performance:</b> Did it respond in under 1000 milliseconds?</li></ul><div className="guide-example"><b>Example result</b><code>PASS · Status is 201</code><code>PASS · JSON contains data.id</code><code>PASS · Response time is below 1000 ms</code></div></section>
        <section id="negative"><p className="guide-label">07 · Negative testing</p><h2>Confirm errors are handled correctly</h2><p>Negative testing intentionally sends invalid or disallowed requests. Start with missing tokens, unknown IDs, validation failures, conflicts, and insufficient funds. Open Advanced HTTP errors to practise forbidden scopes, wrong methods, unsupported content types, rate limiting, and temporary service outages. Inspect headers such as <code>Allow</code>, <code>Retry-After</code>, and <code>X-RateLimit-Remaining</code>.</p></section>
        <section id="postman"><p className="guide-label">08 · Postman</p><h2>Use the live API in Postman</h2><ol><li>Download the Postman collection from the homepage.</li><li>Open Postman and select <b>Import → Files</b>.</li><li>Run <b>Create access token</b>; the token is saved automatically.</li><li>Create a customer and accounts; their IDs are also saved.</li><li>Run and modify any request.</li></ol><div className="guide-callout"><b>Ready-to-use live URL</b><p>The collection already uses <code>https://betappabharath-api-testlab.bharathbetappa.workers.dev</code>. You do not need to run <code>npm run dev</code> or change the <code>baseUrl</code>.</p></div></section>
        <section id="status"><p className="guide-label">09 · Status codes</p><h2>Read the API&apos;s answer</h2><div className="status-reference">{statuses.map(([code,title])=><article key={code}><b>{code}</b><div><h3>{title}</h3><p>{code.startsWith("2") ? "The request succeeded." : "Read the error message and verify why the API rejected it."}</p></div></article>)}</div></section>
        <section id="troubleshooting"><p className="guide-label">10 · Troubleshooting</p><h2>Common issues</h2>{[["The website does not open","Check your internet connection, then reload the live TestLab URL."],["Postman cannot connect","Confirm the collection baseUrl is https://betappabharath-api-testlab.bharathbetappa.workers.dev and that Postman has internet access."],["401 Unauthorized","Run Create access token again and verify Authorization contains Bearer followed by the saved token."],["404 Not Found","Create the customer or account again and confirm that the saved collection variable contains its current ID."],["Delete returns 409","Empty and delete accounts before deleting their customer."],["My records are not visible","Records are isolated by practice token. Use the same unexpired token to access the data created in that session."]].map(([title,copy])=><details key={title}><summary>{title}</summary><p>{copy}</p></details>)}</section>
        <section className="guide-finish"><h2>Ready to practise?</h2><p>Start with a token and sample data, then explore freely.</p><div><a href="/#playground">Open the API Practice Lab</a><a href="https://www.linkedin.com/in/betappa-bharathb111/" target="_blank" rel="noopener noreferrer">Connect with Betappa Bharath on LinkedIn ↗</a></div></section>
      </article>
    </div>
  </main>;
}
